### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ghost** [shubham1898/Instagram-Downloader-react#1]

**Comment by shubham1898** [comment]
Hello, 
If you are trying to install react app on heroku please use a build pack with it. Go to the settings and in BuildPack section add this famous mars build pack link is here - https://github.com/mars/create-react-app-buildpack  , I think then my react will run on heroku.

**Comment by shubham1898** [comment]
hey therealvkr, what api you used to get downloadable link of youtube videos

**Comment by shubham1898** [comment]
Over
